### ISSUE TITLE
CC Steam Beta Branch?

### ISSUE THREAD

**Issue by Mitsuma** [DataRealms/CCOSS#2]
> No game data and most of required runtime DLLs are included, you should get those from the Cortex Command beta branch on Steam.

Any info on how to get the beta branch? There is no beta branch selectable and no code to unlock it anywhere.

**Comment by King-Drake** [comment]
^
Same question.

**Comment by EtiamNullam** [comment]
> Included source code does not match the current B32 functionality. This is a work-in-progress snapshot of what's internally called "B33", so it won't start with data from B32.

> The data can be found under the "ccoss" beta branch of Cortex Command on Steam, if you own a license for the game.

If I get it right: "ccoss" will be the code to access beta branch with game data, but it will be available once update B33 is ready.

**Comment by Smilex** [comment]
I too want access to that beta branch

**Comment by Newk77** [comment]
i remember i had to use a password in Steam to access the beta
googled it and found: rocket100000

**Comment by alrickUA** [comment]
> i remember i had to use a password in Steam to access the beta
> googled it and found: rocket100000

This gave me some OSX builds and that's all (https://i.imgur.com/OJ2bUpn.png)
I've found B33 in unofficial discord: https://discord.gg/y8UBru -- look for latest bundle in #dev-log channel

**Comment by Smilex** [comment]
Thanks for that discord link! The game now runs with my Linux build. See #3

**Comment by data010** [comment]
The steam ccoss beta branch is now live as well, after Valve helped us un-jam it
